### PR TITLE
use WolfLink115's NintendoSwitchPkg instead of imbushuo's

### PR DESCRIPTION
**Pull request by sophuric**
and fix indentation

### CODE REVIEW

**Comment by sophuric** [comment]
> Clone Brotli Inside of edk2 BaseTools and MdeModulePkg if it didn't when cloning

it should clone already since it's recursive, unless you forgot recursive

**Comment by WolfLink115** [comment]
The reason I put "in case it didn't clone brotli" is because I think it cloned an older version of brotli somehow, which didn't caused edk2 to not clone properly. I did use --recursive, otherwise I wouldn't have put those things.

The last time I cloned edk2 it worked fine so yes, I agree that the brotli cloning part should be removed.

**Review by WolfLink115 — COMMENTED** [review]
Is it supposed to take this long to merge?

**Comment by sophuric** [comment]
usually that happens if the submodules aren't up to date, also check .gitmodules

**Pull request merged**
